language: php
sudo: false

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_script:
  - composer update
  - mysql -e 'create database xhprof;'
  - mysql xhprof < ./setup/database.sql

script:
  - php -n ./vendor/bin/athletic --path ./tests/performance/ --bootstrap ./tests/Bootstrap.php --formatter GroupedFormatter
